#!/bin/sh
#
# @name X-UAV Talon 1718 (net interceptor target)
#
# @type Fixedwing
#
# Model: Tools/simulation/interceptor_sim/models/talon1718
#

. ${R}etc/init.d/rc.fw_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=talon1718}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_ARSPDSIM 1

param set-default FW_LND_ANG 8

param set-default FW_PR_FF 0.08
param set-default FW_PR_I 0.3
param set-default FW_PR_P 0.08

param set-default FW_RR_FF 0.05
param set-default FW_RR_I 0.2
param set-default FW_RR_P 0.03

param set-default FW_YR_FF 0.3
param set-default FW_YR_I 0.4
param set-default FW_YR_P 0.2

param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MAX 32
param set-default FW_P_LIM_MIN -15

param set-default FW_AIRSPD_MIN 12
param set-default FW_AIRSPD_TRIM 16
param set-default FW_AIRSPD_MAX 22

param set-default FW_THR_MIN 0.05
param set-default FW_THR_TRIM 0.45
param set-default FW_THR_MAX 1.0

param set-default FW_T_CLMB_R_SP 4
param set-default FW_T_CLMB_MAX 5
param set-default FW_T_SINK_MAX 3
param set-default FW_T_SINK_MIN 2.2

param set-default FW_W_EN 1

# autonomous target: no GCS needed to arm, no datalink-loss failsafe
param set-default NAV_DLL_ACT 0

param set-default RWTO_TKOFF 1

param set-default CA_AIRFRAME 1

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX -0.62

# 0/1 ailerons, 2/3 V-tail ruddervators (no flaps)
param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS2_TRQ_P 0.5
param set-default CA_SV_CS2_TRQ_Y 0.5
param set-default CA_SV_CS2_TYPE 7
param set-default CA_SV_CS3_TRQ_P 0.5
param set-default CA_SV_CS3_TRQ_Y -0.5
param set-default CA_SV_CS3_TYPE 8

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 10
param set-default SIM_GZ_EC_MAX1 1600

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204
